annotation.service.pagesize=1000
annotation.service.timeout=PT2M
media.service.timeout=PT10S
#quarkus.http.cors.access-control-allow-credentials=true
#quarkus.http.cors.headers=Access-Control-Allow-Origin
#quarkus.http.cors.origins=*
#quarkus.http.cors=true
#quarkus.http.header."Access-Control-Allow-Local-Network".value=true
quarkus.http.limits.max-body-size=10M
quarkus.http.port=8080
quarkus.log.level=INFO
quarkus.swagger-ui.always-include=true

# Also supported by Charybdis: SNAKE_CASE
quarkus.jackson.property-naming-strategy=LOWER_CAMEL_CASE
quarkus.jackson.serialization-inclusion=NON_ABSENT
#quarkus.jackson.write-dates-as-timestamps=true
raziel.service.url=http://localhost:8085
raziel.use-internal-urls=false
quarkus.log.category."org.mbari.vars.vampiresquid.sdk".level=INFO
