app:
  greeting: "Hello"

server:
  port: 8080
  host: 0.0.0.0
#  experimental:
#    http2:
#      enable: true
#      max-content-length: 16384

annotation:
  service:
    url: "http://localhost:8082/anno/v1"
    timeout: "PT120S"
    pagesize: 1000

media:
  service:
    url: "http://localhost:8084/vam/v1"
    timeout: "PT10S"
