annotation.service.pagesize=1000
annotation.service.timeout=120
media.service.timeout=10
#quarkus.http.cors.access-control-allow-credentials=true
#quarkus.http.cors.headers=Access-Control-Allow-Origin
#quarkus.http.cors.origins=*
#quarkus.http.cors=true
#quarkus.http.header."Access-Control-Allow-Local-Network".value=true
quarkus.http.limits.max-body-size=10M
quarkus.http.port=8080
quarkus.log.level=DEBUG
quarkus.swagger-ui.always-include=true
quarkus.jackson.serialization-inclusion=NON_ABSENT
#quarkus.jackson.write-dates-as-timestamps=true
raziel.service.url=http://localhost:8085
quarkus.log.category."org.mbari.vars.vampiresquid.sdk".level=DEBUG
